export const items=[
    {
        name:"Circular Decor Wall Mirror",
        image:"images/img1.png",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor tellus id odio pharetra tristique.eget posuere justo luctus",
        quantity:1,
        price:399,
    },
    {
        name:"Hanging Flower Lights",
        image:"images/img3.jpg",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor tellus id odio pharetra tristique.eget posuere justo luctus",
        quantity:1,
        price:149,
    },
    {
        name:"Butterfly Pendant Lights",
        image:"images/img4.jpg",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor tellus id odio pharetra tristique.eget posuere justo luctus",
        quantity:1,
        price:90,
    },
    {
        name:"Standing Decor Mirror",
        image:"images/img5.png",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor tellus id odio pharetra tristique.eget posuere justo luctus",
        quantity:1,
        price:599,
    },
    {
        name:"Butterfly Wall Lamp",
        image:"images/img6.jpg",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor tellus id odio pharetra tristique.eget posuere justo luctus",
        quantity:1,
        price:200,
    },
    {
        name:"Velvet Cushion",
        image:"images/img7.jpg",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor tellus id odio pharetra tristique.eget posuere justo luctus",
        quantity:1,
        price:149,
    },
    {
        name:"Wall Clock",
        image:"images/img8.jpg",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor tellus id odio pharetra tristique.eget posuere justo luctus",
        quantity:1,
        price:199,
    },
    {
        name:"Serving Tray",
        image:"images/img9.jpg",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor tellus id odio pharetra tristique.eget posuere justo luctus",
        quantity:1,
        price:500,
    },
    {
        name:"White Table Vase",
        image:"images/img10.jpg",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor tellus id odio pharetra tristique.eget posuere justo luctus",
        quantity:1,
        price:399,
    },
    {
        name:"Paintings Set of 3",
        image:"images/img11.jpg",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor tellus id odio pharetra tristique.eget posuere justo luctus",
        quantity:1,
        price:799,
    },
    {
        name:"Side Table Vase",
        image:"images/img12.jpg",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor tellus id odio pharetra tristique.eget posuere justo luctus",
        quantity:1,
        price:200,
    },
    {
        name:"Kitchen Spoon",
        image:"images/img2.jpg",
        desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor tellus id odio pharetra tristique.eget posuere justo luctus",
        quantity:1,
        price:899,
    },
]